name: glamourapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  camera: ^0.11.0
  path_provider: ^2.1.5
  http: ^1.1.0
  fluttertoast: ^8.2.2
  firebase_auth: ^5.5.1
  image_picker: ^1.0.4
  image: ^4.5.3
  lucide_icons: ^0.257.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  tflite_flutter: ^0.11.0
  flutter_mediapipe: ^0.0.7
  provider: ^6.1.3
  shared_preferences: ^2.5.3
  flutter_expandable_fab: ^2.5.1
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  flutter_animate: ^4.5.2
  typewritertext: ^3.0.9
  shimmer_animation: ^2.2.2
  bouncing_widget: ^2.0.0
  loading_animation_widget: ^1.3.0
  better_image_shadow: ^0.0.3
  animations: ^2.0.11
  google_ml_kit: ^0.20.0
  animated_size_and_fade: ^5.1.1
  http_parser: ^4.1.2
  fl_chart: ^1.0.0

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/undertone.png
    - assets/glam_logo.png
    - assets/foundation.png
    - assets/concealer.png
    - assets/contour.png
    - assets/eyeshadow.png
    - assets/blush.png
    - assets/lipstick.png
    - assets/highlighter.png
    - assets/eyebrow.png
    - assets/makeup1.jpg
    - assets/makeup2.jpg
    - assets/makeup3.jpg
    - assets/makeup4.jpg
    - assets/makeup5.jpg
    - assets/makeup6.jpg
    - assets/makeup7.jpg
    - assets/makeup8.jpg
    - assets/makeup9.jpg
    - assets/makeup10.jpg
    - assets/makeup11.jpg
    - assets/makeup_faceshapes.jpg
    - assets/guide_lips.jpg
    - assets/eyeshadow.jpg
    - assets/mestiza1.jpg
    - assets/morena.jpg
    - assets/chinita.jpg
    - assets/media.jpg
    - assets/glamour.png
    - assets/facscan_icon.gif
    - assets/camera.png
    - assets/homeg.png
    - assets/profile.png
    - assets/warning1.png
    - assets/card.jpg
    - assets/face shape 2.png
    - assets/skin tone 2.png
    - assets/makeup look.png
    - assets/phone_bg.png
    - assets/phone.png
    - assets/frame3.png
    - assets/oval.png
    - assets/round.png
    - assets/heart.png
    - assets/square.png
    - assets/oblong.png 
    - assets/ovalt_image.png
    - assets/round2_image.png
    - assets/square2_image.png
    - assets/heart2_image.png
    - assets/oblong2_image.png
    - assets/undertone guide.png
    - assets/Mestiza-tone.jpg
    - assets/Chinita-tone.jpg
    - assets/Morena-tone.jpg
    - assets/mestiza-ic.png
    - assets/morena-ic2.png
    - assets/chinita-ic.png
    - assets/vein_step1.jpg
    - assets/vein_step2.jpg
    - assets/vein_step3.jpg
    - assets/vein_step4.jpg
    - assets/jewelry_step1.jpg
    - assets/jewelry_step2.jpg
    - assets/jewelry_step3.jpg
    - assets/jewelry_step4.jpg
    - assets/jewelry_step5.jpg
    


   
    
  
   
    
